In [43]:
import options_q as opt




Problem 1


1a
Completed the function european_binomial_pricer in the options.py module to implement the muliperiod European binomial pricing model


1 b


In [38]:
spot=100.0
strike=105.0
rate=.08
expiry=1.0
nper=1
div=0.0
vol=.2



In [39]:
h = expiry/nper
h

1.0

In [40]:
spot_t = np.zeros(nper + 1)
spot_t

array([0., 0.])

In [42]:

u = np.exp(((rate - div) *h) + (vol * math.sqrt(h)))
u

1.3231298123374369

In [44]:
up = spot * math.exp(((rate - div)*h)+ (vol*math.sqrt(h)))
up

132.3129812337437

In [46]:
d = math.exp(((rate - div)*h)- (vol* math.sqrt(h)))
d

0.8869204367171575

In [47]:
down = spot * math.exp(((rate- div)*h)-(vol*math.sqrt(h)))
down

88.69204367171575

In [48]:
nodes = nper + 1
nodes

2

In [50]:
for t in range(nodes):
    prc = spot * (u**(nper - t))*(d**t)
    print (prc)

132.3129812337437
88.69204367171575


In [51]:
for t in range(nodes):
    spot_t[t] = spot * (u**(nper-t)) * (d**t)

In [52]:
spot_t

array([132.31298123,  88.69204367])

In [53]:
call_t = opt.call_payoff(spot_t, strike)
call_t

array([27.31298123,  0.        ])

In [54]:
pstar= (math.exp((rate-div)*h)-d)/(u-d)
pstar

0.4501660026875224

In [57]:
spot_t = 0.0

In [59]:
call_t = 0.0

In [60]:
for t in range(nodes):
    spot_t = spot * (u**(nper - t))* (d**t)
    call_t += opt.call_payoff(spot_t, strike) * opt.binom.pmf(nper - t, nper, pstar)

In [61]:
call_t

12.295375583473714

In [62]:
disc= opt.np.exp(-rate*expiry)
price = disc*call_t
price

11.350062186067705

In [63]:
print("the price of the call option by hand is:",price)

the price of the call option by hand is: 11.350062186067705


using the european binomial pricer


In [64]:
call_price = opt.european_binomial_pricer(spot, strike, expiry, rate, div, vol, nper, opt.call_payoff)
print("The price of the call option with the european_binomial_pricer is",call_price)

The price of the call option with the european_binomial_pricer is 11.350062186067705


In [65]:
put_price = opt.european_binomial_pricer(spot, strike, expiry, rate, div, vol, nper, opt.put_payoff)
print("The price of the put option with the european_binomial_pricer is",put_price)

The price of the put option with the european_binomial_pricer is 8.277278556664449


1c

In [66]:
spot=100.0
strike=105.0
rate=.08
expiry=1.0
nper=3
div=0.0
vol=.2
h = expiry/nper
h

0.3333333333333333

In [67]:
call_3_price = opt.european_binomial_pricer(spot, strike, expiry, rate, div, vol, nper, opt.call_payoff)
print("The price of the call option with the european_binomial_pricer is",call_3_price)

The price of the call option with the european_binomial_pricer is 10.044685209190389


In [69]:
put_3_price = opt.european_binomial_pricer(spot, strike, expiry, rate, div, vol, nper, opt.put_payoff)
print("The price of the put option with the european_binomial_pricer is",put_3_price)

The price of the put option with the european_binomial_pricer is 6.9719015797871595


1d

In [70]:
spot=100.0
strike=105.0
rate=.08
expiry=1.0
nper=200
div=0.0
vol=.2
h = expiry/nper
h

0.005

In [71]:
call_200_price = opt.european_binomial_pricer(spot, strike, expiry, rate, div, vol, nper, opt.call_payoff)
print("The price of the call option with the european_binomial_pricer is",call_200_price)

The price of the call option with the european_binomial_pricer is 9.471909781165479


In [72]:
put_200_price = opt.european_binomial_pricer(spot, strike, expiry, rate, div, vol, nper, opt.put_payoff)
print("The price of the put option with the european_binomial_pricer is",put_200_price)

The price of the put option with the european_binomial_pricer is 6.399126151760387


## Problem 2


2a

In [73]:
spot=100.0
strike=105.0
rate=.08
expiry=1.0
nper=1
div=0.0
vol=.2
h = expiry/nper
h

1.0

In [74]:
# Call
bs_call = opt.black_scholes_call(spot, strike, expiry, rate, div, vol)
print("using the black scholes pricing model the call option price is",bs_call)

using the black scholes pricing model the call option price is 9.47455279837039


In [75]:
## Put
bs_put = opt.black_scholes_put(spot, strike, expiry, rate, div, vol)
print("using the black scholes pricing model the put option price is", bs_put)

using the black scholes pricing model the put option price is 6.401769168967142


2b

See Excel forthe table

the european binomial has more of a variance as you go along the number. It will also decline over time. The black scholes model doesn't show any variance when looking at a 4 decimal rounding. If you go out more decimal points there will be some change. They do cross at n = 120 and then the European dips a little more but levels off equal to the black schoes at n = 200.

In [76]:
spot=100.0
strike=105.0
rate=.08
expiry=1.0
nper=100
div=0.0
vol=.2
h = expiry/nper
h

0.01

In [77]:
table = opt.european_binomial_pricer(spot,strike, expiry, rate, div, vol, nper, opt.call_payoff)
table

9.481664314226622

In [78]:
spot=100.0
strike=105.0
rate=.08
expiry=1.0
nper=140
div=0.0
vol=.2
h = expiry/nper
h

0.007142857142857143

In [79]:
## Call
bs_call = opt.black_scholes_call(spot, strike, expiry, rate, div, vol)
print("using the black scholes pricing model the call option price is", bs_call)

using the black scholes pricing model the call option price is 9.47455279837039
